Tarea #28 de la Historia #4 "Subir contenido del curso"
abmodelis/abmodelis.github.io pull request #16
Opened 2024-04-20 00:16 UTC by RobertoCarlosFC

#28 Implementar la nueva vista de los cursos creados

2024-04-20 15:01 UTC, julio7173 requested changes
Parece que todo esta bien, pero debes hacer los cambos que te comento.

2024-04-20 15:01 UTC, TOMOKI977 commented on src/views/teachers/courses.tsx
> +              <CardActions sx={{ justifyContent: "space-between" }}>
Esto esta bien, hace lo que se requiere.

2024-04-20 15:01 UTC, julio7173 commented on src/main.tsx
> +//import Teachers from "views/teachers";
Esto lo debes de descomentar, porque sino, no se mostrara nada

2024-04-20 15:01 UTC, julio7173 commented on src/main.tsx
> +    {<App />}
Debes de quitar las llaves, ya que son innecesarias

2024-04-21 03:04 UTC, willypaz243 requested changes
Resuelve los comentarios

2024-04-23 07:52 UTC, julio7173 approved these changes
Excelente, buen trabajo 👍

2024-04-24 01:43 UTC, julio7173 approved these changes
Excelente

2024-04-24 01:43 UTC, amodelpiano1 approved these changes

2024-04-24 02:03 UTC, AnayeliQuispe approved these changes
Esta bien.

2024-04-24 02:04 UTC, Isaac-sys-2023 commented
Esta bien

2024-04-24 02:06 UTC, Isaac-sys-2023 approved these changes

2024-04-24 02:07 UTC, willypaz243 approved these changes

2024-04-24 02:10 UTC, merged