Tarea #30 y #31 de la Historia #4 "Subir Contenido del curso"
abmodelis/abmodelis.github.io pull request #17
Opened 2024-04-21 02:40 UTC by Isaac-sys-2023

En "src/components/CourseData/index.tsx" se agregó los botones de "agregar sección", "cancelar" y "guardar", ademas de algunas "const" para administrar bien las aperturas del modal.
En "src/components/forms/CourseForm.tsx" se agregó el subtítulo para la imagen miniatura que pidió la ingeniera.
Se creo la carpeta "src/components/sections" que se encarga de las secciones de la historia 4
Se creo el componente "src/components/sections/CreateSection.tsx" que es el modal para crear y editar secciones/clases y contiene el título que es un prop y otro componente que se encarga de manejar los inputs ademas de los botones de guardar y cancelar.
Se creo el componente "src/components/sections/Section.tsx" que es una copia de "src/components/CourseData/index.tsx" solo que fue usado para verificar si los cambios hechos en "src/components/CourseData/index.tsx" afectaban en algo su estructura esto debido a que no me corría el backend.
Se creo el componente "src/components/sections/SectionCourse.tsx" que es el encargado de tener clases dentro de las secciones.
Se creo el componente "src/components/sections/SectionForm.tsx" que es el componente encargado de la entrada del título de la seccción/clase.
Se creo el componente "src/components/sections/SectionMaterial.tsx" que es el encargado de contener los materiales/videos y de la caja para agregar archivos.

2024-04-21 03:05 UTC, willypaz243 commented on src/App.tsx
> +    </HashRouter>
Corrige este espacio

2024-04-21 03:06 UTC, willypaz243 requested changes
Por buenas practicas hay quitar el código que esté comentado.

2024-04-27 11:11 UTC, julio7173 approved these changes
Eggcellent, cre

2024-04-27 11:19 UTC, willypaz243 approved these changes

2024-04-27 11:34 UTC, willypaz243 approved these changes

2024-04-27 11:39 UTC, willypaz243 approved these changes

2024-04-27 11:39 UTC, merged